import type { PortfolioData } from "./types";

/**
 * Rakasiwi Surya's CV content. This is the single source of truth that:
 *  - renders instantly on the public page (so HR always sees a full CV, even
 *    before any Firestore writes or with JavaScript disabled), and
 *  - seeds Firestore via the admin "Import starter data" button.
 *
 * Once Firestore has documents in a collection, those override these defaults.
 */
export const defaultData: PortfolioData = {
  profile: {
    name: "Rakasiwi Surya",
    headline: "Software Engineer",
    heroDescription:
      "Software Engineer with 4+ years of experience building web and mobile applications with React JS, Next JS, Node JS, Express JS, React Native, .Net Core, and Go Fiber. AI Enthusiast.",
    aboutDescription:
      "Software Engineer experienced in delivering enterprise, government, and healthcare applications — from ticketing platforms and smart warehouse IoT systems to HRIS, finance, and medical record applications. Comfortable owning both frontend and backend, migrating legacy systems, containerizing deployments with Docker and CI/CD, and collaborating closely with stakeholders to turn business requirements into scalable technical solutions. Ready to relocate overseas.",
    avatarUrl: "/profile.png",
    cvUrl: "https://drive.google.com/file/d/1nUhW_W0RWScAdF7tlZXbGPwQfWzwr_cz/view?usp=sharing",
    email: "rakasiwi.surya@gmail.com",
    phone: "+6285715519890",
    location: "Bekasi, Jawa Barat, Indonesia (Ready to relocate overseas)",
  },
  socials: [
    { id: "linkedin", platform: "linkedin", url: "https://www.linkedin.com/in/rakasiwisurya", order: 0 },
    { id: "github", platform: "github", url: "https://github.com/rakasiwisurya", order: 1 },
    { id: "whatsapp", platform: "whatsapp", url: "https://wa.me/6285715519890", order: 2 },
    { id: "email", platform: "email", url: "mailto:rakasiwi.surya@gmail.com", order: 3 },
  ],
  experiences: [
    {
      id: "exp-cipta",
      company: "PT. Cipta Integrasi Nusantara",
      position: "Technical Lead (Frontend Developer)",
      location: "Remote",
      startDate: "2025-07-21",
      endDate: "2026-03-21",
      summary:
        "Led frontend development for Medora, a hospital management system — bridging frontend and backend teams on API integration, driving technical decisions on UI and state management, and directing localization and non-BPJS adaptation for hospital tenders in Timor-Leste.",
      order: 0,
    },
    {
      id: "exp-liga",
      company: "PT. Liga Indonesia Baru (ILeague)",
      position: "System Development",
      location: "Jakarta, Indonesia",
      startDate: "2024-09-02",
      endDate: "2025-07-18",
      summary:
        "Led the full revamp of the internal HRIS from CodeIgniter 3 & MySQL to Next.js, Express.js, and Microsoft SQL Server as a solo fullstack developer, including infrastructure migration and CI/CD automation.",
      order: 1,
    },
    {
      id: "exp-diksha",
      company: "PT. Diksha Teknologi Indonesia",
      position: "Fullstack Developer",
      location: "Jakarta, Indonesia",
      startDate: "2024-01-08",
      endDate: "2024-08-30",
      summary:
        "Developed Xtra Non Trade, a web-based finance application for PT. Lion Super Indo, covering supplier invoice claim submissions and payment processes with SAP and DJP Indonesia integrations.",
      order: 2,
    },
    {
      id: "exp-nutech",
      company: "PT. Nutech Integrasi (Telkom Group)",
      position: "ReactJS Developer / Technical Lead (Acting)",
      location: "Jakarta, Indonesia",
      startDate: "2022-01-03",
      endDate: "2024-01-02",
      summary:
        "Built and maintained web and mobile applications for government and enterprise clients including DAMRI, Ministry of Transportation, Telkom Akses, Transjakarta, and Customs & Excise (Bea Cukai).",
      order: 3,
    },
  ],
  projects: [
    {
      id: "prj-medora",
      title: "Medora — Medical Records Application",
      company: "PT. Cipta Integrasi Nusantara",
      description:
        "Medora is a hospital management system supporting multiple roles — Administrators, Nurses (Emergency, Outpatient, Inpatient), Doctors, Pharmacy staff, and Admission officers. It integrates doctor schedules, SOAP medical documentation, nursing services, medical equipment tracking, patient medical records, and prescription handling forwarded to the pharmacy, ensuring a smooth patient journey from registration through consultation, treatment, and counter services.",
      responsibilities: [
        "Led frontend development efforts for the Medora application, ensuring scalable architecture, maintainable code structure, and alignment with project requirements",
        "Acted as a bridge between frontend and backend teams, coordinating API integration and enabling parallel development to accelerate delivery timelines",
        "Drove technical decisions on UI implementation, component structure, and state management to improve performance and usability",
        "Maintained hands-on contribution by implementing features, resolving complex bugs, and ensuring high code quality across modules",
        "Oversaw system stability and troubleshooting, proactively identifying and resolving issues to ensure reliability in critical healthcare workflows",
        "Led localization and internationalization efforts, translating medical terminology and application content into standardized English aligned with global healthcare practices",
        "Directed system adaptation for non-BPJS environments, removing and redesigning workflows to meet regulatory and operational requirements for Timor-Leste hospital tenders",
        "Collaborated with stakeholders and cross-functional teams to align business requirements with technical solutions, ensuring smooth delivery and user acceptance",
      ],
      techStack: ["TypeScript", "React JS", "Express JS", "dayjs", "Radix UI", "PostgreSQL"],
      teamSize: 7,
      periodStart: "2025-07-01",
      periodEnd: "2026-03-21",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: true,
      order: 0,
    },
    {
      id: "prj-hris",
      title: "HRIS — PT. Liga Indonesia Baru",
      company: "PT. Liga Indonesia Baru (ILeague)",
      description:
        "Human Resource Information System (HRIS) is an internal enterprise application managing end-to-end employee administration: duty assignments and scheduling, leave management, daily-based overtime packages, attendance and absence tracking, and approval workflows. Includes a centralized employee database, organizational structure management, dynamic role-based access, and a master holiday system with Google Calendar integration.",
      responsibilities: [
        "Led the full revamp of the HRIS application from CodeIgniter 3 & MySQL to Next.js, Express.js, and Microsoft SQL Server",
        "Designed and implemented both frontend and backend architectures as a Fullstack Developer",
        "Maintained the legacy HRIS (CodeIgniter) during migration, fixing critical bugs and shipping urgent HR features",
        "Migrated server infrastructure from Windows Server to Ubuntu Server",
        "Converted manual FTP-based deployments into automated GitLab CI/CD pipelines",
        "Containerized applications and services using Docker",
        "Designed and implemented RESTful APIs for HR modules and business logic",
        "Implemented dynamic user management with role-based access control (RBAC) and Google Calendar holiday imports",
      ],
      techStack: [
        "TypeScript",
        "Next JS",
        "Ant Design",
        "Tailwind CSS",
        "Redux Toolkit",
        "Express JS",
        "Docker",
        "GitLab CI/CD",
        "MySQL",
        "Microsoft SQL Server",
        "CodeIgniter",
        "Ubuntu Server",
      ],
      teamSize: 1,
      periodStart: "2024-09-01",
      periodEnd: "2025-07-18",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: true,
      order: 1,
    },
    {
      id: "prj-xtra",
      title: "Xtra Non Trade — PT. Lion Super Indo",
      company: "PT. Diksha Teknologi Indonesia",
      description:
        "A web-based finance application facilitating supplier invoice claim submissions and payment processes for service and non-trade goods claims. Replaces the manual process where suppliers attended the Head Office in person. Integrates with PT. Lion Super Indo's SAP system for payment data, internal email notification services, centralized user administration, and DJP Indonesia APIs for tax document validation.",
      responsibilities: [
        "Built the frontend supplier portal using Next.js, ensuring a responsive and user-friendly experience",
        "Developed backend services using .NET Core Web API",
        "Implemented business logic using stored procedures and functions in PostgreSQL",
        "Integrated with SAP and DJP Indonesia APIs for payment and tax document validation",
        "Integrated internal Email API with MongoDB for email and activity logging",
      ],
      techStack: [
        "TypeScript",
        "Next JS",
        "NextUI",
        "Tailwind CSS",
        "Redux Toolkit",
        ".Net Core Web API",
        "Azure DevOps",
        "MongoDB",
        "Microsoft SQL Server",
        "PostgreSQL",
      ],
      teamSize: 2,
      periodStart: "2024-01-08",
      periodEnd: "2024-08-30",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: true,
      order: 2,
    },
    {
      id: "prj-ceisa",
      title: "Ceisa 4.0 — Customs and Excise (Bea Cukai)",
      company: "PT. Nutech Integrasi (Telkom Group)",
      description:
        "CEISA (Customs-Excise Information System and Automation) 4.0 is a centralized, integrated, automated system by Indonesia's Directorate General of Customs and Excise, a core component of the national single window system. The Production Module tracks raw material mutations, finished goods, rejection/scrap reporting, and compliance auditing for companies under customs supervision.",
      responsibilities: [
        "Led frontend development for the Production Module: UI pattern design, template creation, and collaboration standards",
        "Defined API contracts and coordinated with a 3-person backend team for parallel development",
        "Acted as system analyst and de facto project manager, keeping timelines and task coordination on track",
        "Developed core frontend features within a micro-frontend architecture",
        "Integrated Host-to-Host (H2H) Open API for data exchange with company ERP systems",
      ],
      techStack: ["JavaScript", "React JS", "Ant Design", "Micro-Frontend", "Redux", "Keycloak Auth", "Axios"],
      teamSize: 20,
      periodStart: "2023-07-01",
      periodEnd: "2024-01-02",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: true,
      order: 3,
    },
    {
      id: "prj-tijeku",
      title: "Tijeku Mobile App — Transjakarta",
      company: "PT. Nutech Integrasi (Telkom Group)",
      description:
        "Now officially launched as the Transjakarta app on Google Play Store, this public transportation app enhances the Jakarta commuter experience with journey planning, real-time bus tracking (up to 95% accuracy), digital ticket purchases via TJPay/AstraPay/QRIS Tap, route and stop information, and incident reporting.",
      responsibilities: [
        "Developed and maintained the app using React Native and React Native Paper",
        "Implemented journey planning, real-time bus tracking, digital ticketing, route info, and incident reporting",
        "Collaborated with backend developers to integrate real-time data and ticketing APIs",
        "Conducted debugging, performance optimization, and maintenance for production deployment",
      ],
      techStack: ["TypeScript", "React Native", "React Native Paper", "Redux Toolkit", "Expo", "Axios", "Socket.io"],
      teamSize: 5,
      periodStart: "2023-03-01",
      periodEnd: "2023-07-01",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: true,
      order: 4,
    },
    {
      id: "prj-swh-mobile",
      title: "Smart Warehouse Mobile App — Telkom Akses",
      company: "PT. Nutech Integrasi (Telkom Group)",
      description:
        "Companion app for the Smart Warehouse Management System, focused on real-time monitoring of warehouse security and user authentication management. Provides real-time dashboards and notifications, map-based monitoring of warehouse locations and device status, and biometric/fingerprint and PIN credential registration linked to web-admin users.",
      responsibilities: [
        "Developed and maintained the mobile app with React Native for real-time warehouse monitoring",
        "Implemented biometric/fingerprint and PIN registration linked to web-admin users",
        "Integrated real-time monitoring using Socket.IO for device status updates and event notifications",
      ],
      techStack: ["TypeScript", "React Native", "Native Base", "Redux Toolkit", "Expo", "Axios", "Socket.io"],
      teamSize: 3,
      periodStart: "2023-01-01",
      periodEnd: "2023-03-01",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: false,
      order: 5,
    },
    {
      id: "prj-swh-web",
      title: "Smart Warehouse Management System — Telkom Akses",
      company: "PT. Nutech Integrasi (Telkom Group)",
      description:
        "Web application for configuration, real-time monitoring, and security management of warehouse facilities across Indonesia. Integrates IoT security devices — smart door locks with two-way verification (PIN + biometric), door/contact sensors, smoke detectors, siren strobe alarms, and Zigbee central hubs — with real-time dashboards, map-based visualization, and detailed security event logs powered by Socket.IO.",
      responsibilities: [
        "Developed and maintained the system using Next.js",
        "Implemented real-time monitoring with Socket.IO for live device status and security events",
        "Built monitoring dashboards, map visualization, and security logging features with RBAC",
        "Conducted technical training for field technicians and Telkom Akses regional heads; acted as PIC during team rotation",
      ],
      techStack: ["JavaScript", "Next JS", "Ant Design", "Redux Toolkit", "GitLab CI/CD", "Docker", "Kubernetes", "Socket.io"],
      teamSize: 3,
      periodStart: "2022-07-01",
      periodEnd: "2023-01-01",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: false,
      order: 6,
    },
    {
      id: "prj-sitolaut",
      title: "SITOLAUT — Ministry of Transportation",
      company: "PT. Nutech Integrasi (Telkom Group)",
      description:
        "Government web application supporting sea logistics management for the Ministry of Transportation of Indonesia. SITOLAUT Barang manages transactional and master data for goods transportation (ships, routes, regulatory flows); SITOLAUT Ternak handles livestock shipment management including mortality tracking and compliance.",
      responsibilities: [
        "Maintained and enhanced the SITOLAUT Barang and SITOLAUT Ternak web applications",
        "Developed frontend features using React.js with Bootstrap",
        "Collaborated with the System Analyst on business rules, logistics workflows, and regulatory requirements",
        "Fixed bugs and resolved production issues to ensure system stability",
      ],
      techStack: ["JavaScript", "React JS", "Bootstrap", "Redux"],
      teamSize: 5,
      periodStart: "2022-03-01",
      periodEnd: "2022-07-01",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: false,
      order: 7,
    },
    {
      id: "prj-taas",
      title: "Ticketing as a Service (TaaS) — DAMRI",
      company: "PT. Nutech Integrasi (Telkom Group)",
      description:
        "Proof of Concept web platform for a centralized employee transportation booking system connecting Bekasi City to the Jababeka Industrial Area. The TaaS Web Company application lets companies create, manage, and submit bulk transportation orders for their employees.",
      responsibilities: [
        "Developed TaaS Web Company, the web application for bulk employee transportation orders",
        "Built the frontend using Next.js, Bootstrap, and SCSS",
        "Implemented UI slicing from UI/UX team designs with responsive, consistent interfaces",
        "Coordinated with backend developers to integrate APIs and align data contracts",
      ],
      techStack: ["JavaScript", "Next JS", "Bootstrap", "SCSS", "Redux", "GitLab CI/CD", "Docker"],
      teamSize: 4,
      periodStart: "2022-01-03",
      periodEnd: "2022-03-01",
      imageUrl: "",
      demoUrl: "",
      repoUrl: "",
      featured: false,
      order: 8,
    },
  ],
  education: [
    {
      id: "edu-itbu",
      institution: "Institut Teknologi Budi Utomo",
      degree: "Bachelor of Computer Science",
      fieldOfStudy: "Computer Science",
      startYear: 2016,
      endYear: 2020,
      gpa: "3.85 / 4.00",
      description: "Graduated with The Best Student Predicate.",
      order: 0,
    },
  ],
  skills: [
    { id: "sk-react", name: "React JS", category: "FRONTEND", proficiency: 95, order: 0 },
    { id: "sk-next", name: "Next JS", category: "FRONTEND", proficiency: 95, order: 1 },
    { id: "sk-ts", name: "TypeScript", category: "FRONTEND", proficiency: 90, order: 2 },
    { id: "sk-js", name: "JavaScript", category: "FRONTEND", proficiency: 95, order: 3 },
    { id: "sk-tw", name: "Tailwind CSS", category: "FRONTEND", proficiency: 90, order: 4 },
    { id: "sk-antd", name: "Ant Design", category: "FRONTEND", proficiency: 90, order: 5 },
    { id: "sk-bootstrap", name: "Bootstrap", category: "FRONTEND", proficiency: 85, order: 6 },
    { id: "sk-sass", name: "Sass", category: "FRONTEND", proficiency: 80, order: 7 },
    { id: "sk-node", name: "Node JS", category: "BACKEND", proficiency: 90, order: 8 },
    { id: "sk-express", name: "Express JS", category: "BACKEND", proficiency: 90, order: 9 },
    { id: "sk-nest", name: "Nest JS", category: "BACKEND", proficiency: 80, order: 10 },
    { id: "sk-dotnet", name: ".Net Core API", category: "BACKEND", proficiency: 80, order: 11 },
    { id: "sk-php", name: "PHP", category: "BACKEND", proficiency: 80, order: 12 },
    { id: "sk-ci", name: "CodeIgniter", category: "BACKEND", proficiency: 80, order: 13 },
    { id: "sk-go", name: "Golang", category: "BACKEND", proficiency: 75, order: 14 },
    { id: "sk-fiber", name: "Go Fiber", category: "BACKEND", proficiency: 75, order: 15 },
    { id: "sk-python", name: "Python", category: "BACKEND", proficiency: 70, order: 16 },
    { id: "sk-pg", name: "PostgreSQL", category: "DATABASE", proficiency: 85, order: 17 },
    { id: "sk-mysql", name: "MySQL", category: "DATABASE", proficiency: 85, order: 18 },
    { id: "sk-mssql", name: "MS SQL Server", category: "DATABASE", proficiency: 85, order: 19 },
    { id: "sk-mongo", name: "MongoDB", category: "DATABASE", proficiency: 80, order: 20 },
    { id: "sk-prisma", name: "ORM Prisma", category: "DATABASE", proficiency: 85, order: 21 },
    { id: "sk-sequelize", name: "ORM Sequelize", category: "DATABASE", proficiency: 85, order: 22 },
    { id: "sk-docker", name: "Docker", category: "DEVOPS", proficiency: 85, order: 23 },
    { id: "sk-gitlab", name: "GitLab CI/CD", category: "DEVOPS", proficiency: 85, order: 24 },
    { id: "sk-azure", name: "Azure DevOps", category: "DEVOPS", proficiency: 75, order: 25 },
    { id: "sk-ubuntu", name: "Ubuntu Server", category: "DEVOPS", proficiency: 80, order: 26 },
    { id: "sk-winserver", name: "Windows Server", category: "DEVOPS", proficiency: 75, order: 27 },
    { id: "sk-rn", name: "React Native", category: "MOBILE", proficiency: 85, order: 28 },
    { id: "sk-figma", name: "Figma (UI/UX)", category: "OTHER", proficiency: 80, order: 29 },
    { id: "sk-ai", name: "AI", category: "OTHER", proficiency: 75, order: 30 },
  ],
  certificates: [
    { id: "cert-dicoding-fe", title: "Frontend Web Developer Expert", issuer: "Dicoding", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 0 },
    { id: "cert-dicoding-ai", title: "Basic of AI (Artificial Intelligence)", issuer: "Dicoding", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 1 },
    { id: "cert-dicoding-be", title: "Backend Application", issuer: "Dicoding", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 2 },
    { id: "cert-dicoding-aws", title: "Cloud Practitioner Essential (AWS)", issuer: "Dicoding", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 3 },
    { id: "cert-dicoding-gcp", title: "Google Cloud Platform (GCP)", issuer: "Dicoding", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 4 },
    { id: "cert-alibaba-aca", title: "ACA (Alibaba Cloud Associate)", issuer: "Alibaba Cloud", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 5 },
    { id: "cert-alibaba-acp", title: "ACP (Alibaba Cloud Professional)", issuer: "Alibaba Cloud", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 6 },
    { id: "cert-dumbways", title: "Fullstack Developer", issuer: "Bootcamp Dumbways", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 7 },
    { id: "cert-hacktiv8", title: "Website Application Development", issuer: "Hacktiv8 Online Learning", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 8 },
    { id: "cert-dts", title: "HTML, CSS, Javascript", issuer: "DTS (Digital Talent Scholarship)", kind: "CERTIFICATE", issueDate: "", credentialUrl: "", order: 9 },
    { id: "cert-denso", title: "Global Denso Energy Saving Design Poster Competition (ASIA REGIONAL AWARD)", issuer: "DENSO CORPORATION", kind: "AWARD", issueDate: "", credentialUrl: "", order: 10 },
  ],
};
